### PR TITLE
Lua syntax highlighting on loadstring is the best change

### PR DESCRIPTION
**Pull request by joeengo**

### CODE REVIEW

**Comment by Roblox-Thot** [comment]
This update fixed my loneliness, I now have lots of friends thanks to this.

**Comment by zwinplayer64** [comment]
This ended my depression, thanks

**Comment by 7GrandDadPGN** [comment]
bruh

**Comment by DataM0del** [comment]
Complain about me formatting and then make a change that only adds syntax highlighting.
Also, `luau`, not `lua`.

**Comment by joeengo** [comment]
> Complain about me formatting and then make a change that only adds syntax highlighting. Also, `luau`, not `lua`.

shut ur mouth stupid fucker

**Pull request merged**
