### PR TITLE
Update 9544666096.lua

### PR DESCRIPTION
**Pull request by Toon-arch**

### CODE REVIEW

**Review by 7GrandDadPGN — CHANGES_REQUESTED** [review]
no task.spawn? LOOL

**Review by 7GrandDadPGN — APPROVED** [review]
no, don't do that please
L + ratio

**Comment by joeengo** [comment]
bhcgfhbvxcbxbdxf

**Comment by trollfacenan** [comment]
dydtygfgherrwqtrsf

**Pull request merged**
