### PR TITLE
Update all requests

### PR DESCRIPTION
**Pull request by Roblox-Thot**
Update requests to use the newest Commit hash

### CODE REVIEW

**Review by trollfacenan — CHANGES_REQUESTED** [review]
make bedwarsdata use main, otherwise it won't be updated realtime

**Comment by trollfacenan** [comment]
> make bedwarsdata use main, otherwise it won't be updated realtime

(it should not)

**Comment by Roblox-Thot** [comment]
> make bedwarsdata use main, otherwise it won't be updated realtime

👍 didn't think about that when I mass changed them all.

**Comment by joeengo** [comment]
should probably also be a shared variable (shared.VapeGitCommitHash) or similar because reading the files over probably isnt the best option lol

**Comment by Roblox-Thot** [comment]
> should probably also be a shared variable (shared.VapeGitCommitHash) or similar because reading the files over probably isnt the best option lol

If he wants to do that he can 🤷 I'm not going to rewrite his stuff if he doesn't want it

**Comment by 7GrandDadPGN** [comment]
> 

yeah I'll prob make a shared var instead yeah

**Comment by Roblox-Thot** [comment]
Ight

**Pull request closed without merging**
